### ISSUE TITLE
File upload function

### ISSUE THREAD

**Issue by Presleyderrick** [cloudinary/cloudinary-react-native#10]
upload does not seem to work for me, how can I import upload because when I don't I get " Cannot find name 'upload'. "

**Comment by tamaracloudinary** [comment]
Hi there, make sure your code is set up correctly, you can use the upload example here: https://github.com/cloudinary/cloudinary-react-native#usage
If it's set correctly and there is an issue, can you please share your code here?
Thanks
-Tamara

**Comment by Presleyderrick** [comment]
Hi,

this is my code

import { PermissionsAndroid, Text, View } from 'react-native'
import React, { Component, useState } from 'react'
import {Cloudinary} from ***@***.***/url-gen';
import { launchCamera } from 'react-native-image-picker';



const cld = new Cloudinary({
    cloud: {
      cloudName: '<your_cloud_name>'
    },
    url: {
      secure: true
    }
  });

    const uploademp =()=> {
        const [photoPath, setPhotoPath] = useState<string | undefined>(
undefined);

        const cloudinaryUpload = async () => {

              const options: UploadApiOptions = {
                upload_preset: 'sample_preset',
                unsigned: true,
              }

                await upload(cld, {file: photoPath , options: options,
callback: (error: any, response: any) => {
                    //.. handle response
                }})
        };


            const openCamera = async () => {
                const granted = await PermissionsAndroid.request(
                  PermissionsAndroid.PERMISSIONS.CAMERA,
                );
                if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                  const result = await launchCamera(options);
                  // const currentDate = new Date();
                  // const formattedDate = format(currentDate,
'yyyyMMddHHmmss');
                  // const newPhotoPath = `e_permit${formattedDate}.jpg`;

                  try {
                    if (result && result.assets && result.assets[0]) {
                      // const newPath =
`${RNFS.DocumentDirectoryPath}/${newPhotoPath}`;
                      // await RNFS.moveFile(result.assets[0].uri, newPath);
                      setPhotoPath(result.assets[0].uri);
                      // console.log("response is:", uri);
                      const base64Image = result.assets[0].base64;
                      // console.log('Error renaming photo:', base64Image);
                      const source = {
                        base64Image
                      };
                      cloudinaryUpload();
                    } else {
                      console.log('result.assets is undefined or empty.');
                    }
                  } catch (error) {
                    console.log('Error:', error);
                  }
                }
              };

    {
        return (
        <View>
            <Text>uploademp</Text>
        </View>
        )
    }
}

export default uploademp

and this is what I am receiving from my error

Cannot find name 'upload'.ts(2304)
any

Kindly advise on where the error seems to emanate from since I cannot be
able to find any import statement for the upload

Regards,
Presley Derrick.
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
08/15/23,
12:47:32 PM

**Comment by tamaracloudinary** [comment]
In your code, you have to update the 'upload_preset' with your own, the cloud name with your own and import Cloudinary this way: `import {Cloudinary} from '@cloudinary/url-gen';`. Also, implement what happens inside the upload function. 
Please try these and let me know how it goes. 
Thanks, 
- Tamara

**Comment by Presleyderrick** [comment]
Hello,

This is what I have

import { PermissionsAndroid, Text, View } from 'react-native'
import React, { Component, useState } from 'react'
import {Cloudinary} from ***@***.***/url-gen';
import { launchCamera } from 'react-native-image-picker';



  const cld = new Cloudinary({

    cloud: { cloudName: 'dtauszhrv'  },

    url: { secure: true }

  });

  interface UploadApiOptions {
    upload_preset: string;
    unsigned: boolean;
  }


    const uploademp =()=> {
        const [photoPath, setPhotoPath] = useState<string | undefined>(
undefined);

        const cloudinaryUpload = async () => {

  const cloudoptions: UploadApiOptions = {

    upload_preset: 'e-permit',

    unsigned: true,

  }

                await upload(cld, {file: photoPath , options: options,
callback: (error: any, response: any) => {
                    //.. handle response
                }})
        };


            const openCamera = async () => {
                const granted = await PermissionsAndroid.request(
                  PermissionsAndroid.PERMISSIONS.CAMERA,
                );
                if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                  const result = await launchCamera(options);
                  // const currentDate = new Date();
                  // const formattedDate = format(currentDate,
'yyyyMMddHHmmss');
                  // const newPhotoPath = `e_permit${formattedDate}.jpg`;

                  try {
                    if (result && result.assets && result.assets[0]) {
                      // const newPath =
`${RNFS.DocumentDirectoryPath}/${newPhotoPath}`;
                      // await RNFS.moveFile(result.assets[0].uri, newPath);
                      setPhotoPath(result.assets[0].uri);
                      // console.log("response is:", uri);
                      const base64Image = result.assets[0].base64;
                      // console.log('Error renaming photo:', base64Image);
                      const source = {
                        base64Image
                      };
                      cloudinaryUpload();
                    } else {
                      console.log('result.assets is undefined or empty.');
                    }
                  } catch (error) {
                    console.log('Error:', error);
                  }
                }
              };

    {
        return (
        <View>
            <Text>uploademp</Text>
        </View>
        )
    }
}

export default uploademp I am still getting the same error, Kindly advice
on a solution Regards, Derrick Presley



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
08/21/23,
02:28:12 PM

**Comment by tamaracloudinary** [comment]
Hello,

Please proceed with the changes I suggested. Once you've done that, please let me know if the issue persists. 

Best regards,
Tamara

**Comment by Presleyderrick** [comment]
Hi,

I made the suggested changes please send me the code example perhaps
there's something I am missing from mine. Just edit mine as it is and
re-send it to me then I will let you know if it works.

Thanks.

Regards.

**Comment by tamaracloudinary** [comment]
This is the relevant part you should change in your code: 

`import {Cloudinary} from '@cloudinary/url-gen';
import { launchCamera } from 'react-native-image-picker';

  const cld = new Cloudinary({
    cloud: {
      cloudName: 'dtauszhrv'
    },
    url: {
      secure: true
    }
  });

    const cloudinaryUpload = async () => {
            const options: UploadApiOptions = {
              upload_preset: 'e-permit',
              unsigned: true,

            }

    await upload(cld, {file: photoPath , options: options,callback: (error: any, response: any) => {
                    //.. handle response
                }})
        };
`

**Comment by Presleyderrick** [comment]
What should I change it to. The issue is with the upload line

**Comment by Presleyderrick** [comment]
Hi,

This is my full code, If you can take a look at the other camera option it
has imports for its options settings and launch settings,

please recheck the options for the upload since I am still having the same
issue

import { PermissionsAndroid, Text, TouchableOpacity, View } from
'react-native'
import React, { useState } from 'react'
import {Cloudinary} from ***@***.***/url-gen';
import { ImageLibraryOptions, launchCamera } from
'react-native-image-picker';



const cld = new Cloudinary({
  cloud: {
  cloudName: 'dtauszhrv'
  },
  url: {
  secure: true
  }
  });

    const uploademp =()=> {
        const [photoPath, setPhotoPath] = useState<string | undefined>(
undefined);

        const cloudinaryUpload = async () => {
          const options: UploadApiOptions = {
            upload_preset: 'e-permit',
            unsigned: true,

          }

      await upload(cld, {file: photoPath , options: options,callback: (error
: any, response: any) => {
        if (error) {
            console.log("Error:", error);
        } else {
            console.log("Response:", response);
        }
              }})
      };


      const imageoptions: ImageLibraryOptions = {
        mediaType: 'photo',
        maxWidth: 500,
        maxHeight: 500,
        includeBase64: true
      };
      const openCamera = async () => {
        const granted = await PermissionsAndroid.request(
             PermissionsAndroid.PERMISSIONS.CAMERA,
        );
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        const result = await launchCamera(imageoptions);
                  // const currentDate = new Date();
                  // const formattedDate = format(currentDate,
'yyyyMMddHHmmss');
                  // const newPhotoPath = `e_permit${formattedDate}.jpg`;

          try {
                if (result && result.assets && result.assets[0]) {
                      // const newPath =
`${RNFS.DocumentDirectoryPath}/${newPhotoPath}`;
                      // await RNFS.moveFile(result.assets[0].uri, newPath);
                    setPhotoPath(result.assets[0].uri);
                      // console.log("response is:", uri);
                    const base64Image = result.assets[0].base64;
                      // console.log('Error renaming photo:', base64Image);
                    const source = {
                        base64Image
                      };
                      cloudinaryUpload();
                    } else {
                      console.log('result.assets is undefined or empty.');
                    }
                  } catch (error) {
                    console.log('Error:', error);
                  }
                }
              };

    {
        return (
        <View>
            <Text>uploademp</Text>
            <TouchableOpacity onPress={openCamera}>
              <Text>Say cheese</Text>
            </TouchableOpacity>
        </View>
        )
    }
}

export default uploademp

Attatched are images showing what error I am receiving. I am using a tsx
file

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
08/23/23,
08:07:45 AM

**Comment by tamaracloudinary** [comment]
Hi, the camera is not related to Cloudinary so we can't provide support for it, but your imports still don't include the right import for Cloudinary, please change them from: 

```
import {Cloudinary} from ***@***.***/url-gen';
```
to: 

```
import {Cloudinary} from '@cloudinary/url-gen';
```

**Comment by Presleyderrick** [comment]
The camera is just a refference, please check your mail for  snapshots of the problems I'm facing and give a definitive solution, the import statement is correct as it is in your mail I have no issue with that. The problem is not with the cloudinary tag that works fine, my problem is with the UploadApiOptions and the upload from the await upload. How can I import them??

**Comment by tamaracloudinary** [comment]
Ok, thanks for sharing this screenshot. It's not a Cloudinary-related error. Please take a look at these posts to resolve this: 
https://stackoverflow.com/questions/51158080/typescript-cannot-find-name-errors-in-react-components
https://bobbyhadz.com/blog/react-typescript-cannot-find-name

**Comment by Presleyderrick** [comment]
I am using a tsx file not a ts. I tried it with the links provided but still same error

**Comment by ericyliu** [comment]
im having the same issue and confused as where you are getting the `upload` method from in the line `await upload(cld, {file: photoPath , options: options,callback: (error: any, response: any) => {`

**Comment by tamaracloudinary** [comment]
Hi, I wanted to update you that a fix for the issue was deployed. 
Can you please try and let me know if everything works okay for you now?
Thank you for your patience, and sorry about the late identification of the issue.
Best,
Tamara

**Comment by joemewes** [comment]
I have an issue related as well. It looks like `upload` should be imported from this library.
ie. import { upload } from 'cloudinary-react-native';
as per https://github.com/cloudinary/cloudinary-react-native/blob/master/src/index.tsx.

but when imported we get this error 
```
undefined Unable to resolve module ./../api/upload/model/params/upload-params
```

any suggestions?

**Comment by tamaracloudinary** [comment]
Hi @joemewes, Thank you for bringing this to our attention. The issue has been successfully resolved and deployed. Please upgrade to version 0.1.1.

Cheers!

**Comment by Presleyderrick** [comment]
Hi, so initially the package ran well but on the update to  0.1.1  now I get a 

Could not find a declaration file for module 'cloudinary-react-native'. 'd:/Git_rip/gnovationEPERMIT/node_modules/cloudinary-react-native/lib/commonjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/cloudinary-react-native` if it exists or add a new declaration (.d.ts) file containing `declare module 'cloudinary-react-native';`ts(7016)
![image](https://github.com/cloudinary/cloudinary-react-native/assets/78737701/cdda3233-95f4-409f-a7a9-cb799cba42dd)

**Comment by tamaracloudinary** [comment]
Hi @Presleyderrick, can you please check your `package.json` to make sure that the `cloudinary-react-native` exists and run `npm install` to make sure it’s installed?
Please search the node_modules folder to make sure it’s there.
Thanks, 
Tamara

**Comment by Presleyderrick** [comment]
I did install it, as you can see Import for cloudinary URL gen reads properly

**Comment by tamaracloudinary** [comment]
@Presleyderrick are you sure? can you please run a quick `npm install` to make sure it's installed?
Looking forward to your update

**Comment by Presleyderrick** [comment]
Hi @tamaracloudinary, The image below is a snippet of my package.json file
![image](https://github.com/cloudinary/cloudinary-react-native/assets/78737701/7cce8348-b570-4478-afb4-94e42cac8b7a)

**Comment by tamaracloudinary** [comment]
Hi @Presleyderrick, In order to better understand the issue, I need some more information. 
Can I please ask you to provide more details about the problem you're encountering?
- Tamara

**Comment by tamaracloudinary** [comment]
Thanks @Presleyderrick, we released a new fixed version 0.1.2, can you please try it and let me know how it works?

**Comment by RiteshJariwala** [comment]
I have the following code:

export const uploadImages = async () => {
let files = ['/sdcard/Download/mrousavy1486082660270893213.jpg', '/sdcard/Download/mrousavy167616870848093416.jpg'];
  const cld = new CloudinaryRN({
    cloud: {
      cloudName: cloudName,
    },
    url: {
      secure: true,
    },
  });

  const options = {
    signature: signature,
    timestamp: timestamp,
    api_key: apiKey,
  };
  await upload(cld, {
    file: files[0],
    options: options,
    callback: (error, response) => {
      //.. handle response
      console.log('response', response, error, index);
    },
  });
}

I am getting the following errors and warnings:

 ERROR  Error: Cannot find native module 'ExpoCrypto', js engine: hermes
 
WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'process_request_params' of undefined
TypeError: Cannot read property 'process_request_params' of undefined 

I am having "cloudinary-react-native": "^0.1.2" installed


Any one here to help out?

**Comment by Presleyderrick** [comment]
Hi @momoip is there any update?

**Comment by singhayush1403** [comment]
My uploads are failing on android but working on iOS. any reason why?

**Comment by dannyv-cloudinary** [comment]
Hi @singhayush1403.

Could you please [raise a support ticket with us](https://support.cloudinary.com/hc/en-us/requests/new) including any code samples that may be relevant, so we can look into this in greater detail for you?

Many thanks!
-Danny

**Comment by naveenbhusare** [comment]
@RiteshJariwala  did you found solution for this i as well facing the same issue ?

**Comment by momoip** [comment]
Hi  there,
Thanks for letting us know.  
I'm checking with our Dev team and will let you know.  
Thanks,
Mo

**Comment by momoip** [comment]
Hi @singhayush1403,
We have made the fix for Android.  Please let us know if it works for you.
Regards,
Mo
