### ISSUE TITLE
Update Requirement documentation

### ISSUE THREAD

**Issue by naufanituharish** [cloudinary/cloudinary-react-native#17]
Since it use expo in the development so it needs to configure expo module for the people who are going to use it in bare react native.

And since I do develop the project using bare react native and only need the upload feature so it seems not suitable for me to install the expo module.

Do you have any suggestion for it?

**Comment by rnamba-cloudinary** [comment]
Hey @naufanituharish,

Would you please clarify what the issue is here?

**Comment by naufanituharish** [comment]
Halo there, I was trying to use the react native cloudinary SDK in my react native project. I do develop the project using bare react native, not using expo. I could not use the SDK after installing it. The error said that I need to install expo module. 
So I thought it's better to update the documentation to explain how to use the SDK in react native project that not use expo. 
So it need to install expo module before I can use it in bare react native.
Here is the documentation to install expo module in bare react native
https://docs.expo.dev/bare/installing-expo-modules

Regards,
Naufan Harish

**Comment by atdcloud** [comment]
Hi @naufanituharish , 

Currently our SDK is supported with Expo only.  The decision was not taken lightly, and was following the community best practices.

I hope this helps.

**Comment by naufanituharish** [comment]
That's what I said before, it is only support the development that using expo. So I thought it's better to update the documentation an mention it on the readme. 

Regards,
Naufan Harish

**Comment by tommyg-cld** [comment]
@naufanituharish thx, i will pass that back to our docs team.

**Comment by momohyusuf** [comment]
Please update your documentation soon. I spent the entire night going through your documentation trying to figure out why the upload was not working for me. Just came across this issue now and finally saw it only works with Expo React native project.
