### ISSUE TITLE
Upload Method Expo Error

### ISSUE THREAD

**Issue by gwashburne** [cloudinary/cloudinary-react-native#26]
## Bug report for Cloudinary React Native SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.

Including the upload method results in an Expo error. It's able to build; however, before it ever executes the code calling the upload method, it throws an error. If I comment out the code calling upload, it works fine. I spent a good bit of time updating Expo and installing missing packages, and I'm fairly convinced my Expo setup isn't the problem (note, I'm actually not using Expo managed, I'm just using some of the packages).

## Issue Type (Can be multiple)
[x] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
Call the upload method, imported from cloudinary-react-native, and rebuild

## Error screenshots or Stack Trace (if applicable)

<img width="974" alt="Screenshot 2024-05-28 at 11 59 23 AM" src="https://github.com/cloudinary/cloudinary-react-native/assets/137097545/0d281ae3-a153-4485-b238-94fb9538d890">

## Build/Dependency management
[x] Cocoa-Pods
[ ] Carthage
[ ] Manual import
[x] Other (Specify) - npm

## Is the issue reproducible only on a specific device?
[x] No - same error when trying to run on iOS or Android
[ ] Yes (specify device model + iOS/Android version)

## Versions and Libraries (fill in the version numbers)
React Native Cloudinary SDK version - 1.0.0
OSX (on the dev environment) - 14.5 

Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by tommyg-cld** [comment]
@gwashburne I'm afraid this SDK is supported with Expo only currently so please install that. We apologise for the inconvenience.

**Comment by gwashburne** [comment]
Ah, gotcha. Could that be added to the docs? Maybe I missed it, but it would be super handy if the docs mentioned it.

**Comment by tommyg-cld** [comment]
@gwashburne sure thing, we will be sure to add it to the docs soon. Thank you for the feedback.

**Comment by gwashburne** [comment]
Thank you!
